//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobyClient.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobyClient.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be blank.
        /// </summary>
        internal static string ErrorLogInMissingPassword {
            get {
                return ResourceManager.GetString("ErrorLogInMissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be blank.
        /// </summary>
        internal static string ErrorLogInMissingUsername {
            get {
                return ResourceManager.GetString("ErrorLogInMissingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password not found.
        /// </summary>
        internal static string ErrorLogInUsernamePasswordNotFound {
            get {
                return ResourceManager.GetString("ErrorLogInUsernamePasswordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Code:.
        /// </summary>
        internal static string LabelAreaCode {
            get {
                return ResourceManager.GetString("LabelAreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string LabelCountry {
            get {
                return ResourceManager.GetString("LabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display as:.
        /// </summary>
        internal static string LabelDisplayAs {
            get {
                return ResourceManager.GetString("LabelDisplayAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address:.
        /// </summary>
        internal static string LabelEmailAddress {
            get {
                return ResourceManager.GetString("LabelEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Addresses.
        /// </summary>
        internal static string LabelEmailAddresses {
            get {
                return ResourceManager.GetString("LabelEmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension:.
        /// </summary>
        internal static string LabelExtension {
            get {
                return ResourceManager.GetString("LabelExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        internal static string LabelFirstName {
            get {
                return ResourceManager.GetString("LabelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        internal static string LabelLastName {
            get {
                return ResourceManager.GetString("LabelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Number:.
        /// </summary>
        internal static string LabelLocalNumber {
            get {
                return ResourceManager.GetString("LabelLocalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LabelLogin {
            get {
                return ResourceManager.GetString("LabelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name:.
        /// </summary>
        internal static string LabelMiddleName {
            get {
                return ResourceManager.GetString("LabelMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moby Client Login.
        /// </summary>
        internal static string LabelMobyClientLogin {
            get {
                return ResourceManager.GetString("LabelMobyClientLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Numbers.
        /// </summary>
        internal static string LabelPhoneNumbers {
            get {
                return ResourceManager.GetString("LabelPhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary:.
        /// </summary>
        internal static string LabelPrimary {
            get {
                return ResourceManager.GetString("LabelPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix:.
        /// </summary>
        internal static string LabelSuffix {
            get {
                return ResourceManager.GetString("LabelSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string LabelTitle {
            get {
                return ResourceManager.GetString("LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string LabelType {
            get {
                return ResourceManager.GetString("LabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string LabelUsername {
            get {
                return ResourceManager.GetString("LabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drafts.
        /// </summary>
        internal static string MailboxDrafts {
            get {
                return ResourceManager.GetString("MailboxDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookCircleArrowUp.
        /// </summary>
        internal static string MailboxDraftsIcon {
            get {
                return ResourceManager.GetString("MailboxDraftsIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        internal static string MailboxInbox {
            get {
                return ResourceManager.GetString("MailboxInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InboxIn.
        /// </summary>
        internal static string MailboxInboxIcon {
            get {
                return ResourceManager.GetString("MailboxInboxIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing.
        /// </summary>
        internal static string MailboxOutgoing {
            get {
                return ResourceManager.GetString("MailboxOutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InboxOut.
        /// </summary>
        internal static string MailboxOutgoingIcon {
            get {
                return ResourceManager.GetString("MailboxOutgoingIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        internal static string MailboxPersonal {
            get {
                return ResourceManager.GetString("MailboxPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SquareUser.
        /// </summary>
        internal static string MailboxPersonalIcon {
            get {
                return ResourceManager.GetString("MailboxPersonalIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned Messages.
        /// </summary>
        internal static string MailboxPinnedMessages {
            get {
                return ResourceManager.GetString("MailboxPinnedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbtack.
        /// </summary>
        internal static string MailboxPinnedMessagesIcon {
            get {
                return ResourceManager.GetString("MailboxPinnedMessagesIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string MailboxSent {
            get {
                return ResourceManager.GetString("MailboxSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArrowRightFromBracket.
        /// </summary>
        internal static string MailboxSentIcon {
            get {
                return ResourceManager.GetString("MailboxSentIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam.
        /// </summary>
        internal static string MailboxSpam {
            get {
                return ResourceManager.GetString("MailboxSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban.
        /// </summary>
        internal static string MailboxSpamIcon {
            get {
                return ResourceManager.GetString("MailboxSpamIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        internal static string MailboxTrash {
            get {
                return ResourceManager.GetString("MailboxTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        internal static string MailboxTrashIcon {
            get {
                return ResourceManager.GetString("MailboxTrashIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        internal static string MailboxWork {
            get {
                return ResourceManager.GetString("MailboxWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Briefcase.
        /// </summary>
        internal static string MailboxWorkIcon {
            get {
                return ResourceManager.GetString("MailboxWorkIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string PageCalendar {
            get {
                return ResourceManager.GetString("PageCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string PageContacts {
            get {
                return ResourceManager.GetString("PageContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string PageDashboard {
            get {
                return ResourceManager.GetString("PageDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string PageEmails {
            get {
                return ResourceManager.GetString("PageEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string PageMessages {
            get {
                return ResourceManager.GetString("PageMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string PageSettings {
            get {
                return ResourceManager.GetString("PageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Content.
        /// </summary>
        internal static string PageSharedContent {
            get {
                return ResourceManager.GetString("PageSharedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string PlaceholderPassword {
            get {
                return ResourceManager.GetString("PlaceholderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        internal static string PlaceholderUsername {
            get {
                return ResourceManager.GetString("PlaceholderUsername", resourceCulture);
            }
        }
    }
}
